# Generated by Django 5.2.5 on 2025-08-28 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la zona.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('consumo_maximo_w', models.IntegerField(help_text='Consumo máximo permitido en Watts.')),
                ('estado', models.BooleanField(default=True, help_text='Indica si el dispositivo está activo.')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.categoria')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_w', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('revisada', models.BooleanField(default=False, help_text='Indica si la alerta ha sido revisada.')),
                ('medicion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.medicion')),
            ],
        ),
    ]
